default: &default
  region: "us-east1"
  zone: "us-east1-a"
  gcp:
    project: "hc-public"
    service_account: "~/safe/hc-public/terraform.json"
    bucket_name: "kite-state-helios-devel"
  aws:
    access_key: "********************"
    secret_key: "****************************************"
